<template>
  <div
    class="p-10 bg-gradient-to-b from-slate-900 to-slate-800 w-screen min-h-screen"
  >
    <PageHeader />
    <div class="grid grid-cols-5 m-5 p-5 gap-y-10">
      <ProjectIntro
        :title="title"
        :github="github"
        :images="images"
        :poster="poster"
      />
      <div class="col-span-2 mx-3 pl-4 text-slate-200 text-2xl">
        <h2 class="text-lime-400">Concrete Printing</h2>
        <p class="text-lg mt-4 text-justify">
          I was introduced to the world of Concrete Printing through the LefLab
          that is organised by ICE Cube at Thomas More. The provide
          opportunities for interdisciplinary teams to work together and create
          truly wonderful things. The goal of this project was to improve the
          existing facility and functionalities of the Cobod Concrete Printer
          that was now stationed at Kamp C in Westerlo. These improvements,
          together with a solid business plan, would provide an opportunity to
          bring this technology to the campus and open new doors for future
          students.
        </p>
      </div>
      <div class="col-span-3 mx-3 pl-4">
        <figure>
          <img
            class="object-cover object-left-top rounded-xl drop-shadow-xl"
            src="~/assets/images/3DBetonPrint.jpg"
            alt=""
          />
        </figure>
      </div>
      <div class="col-span-2 col-start-1 mx-3 pl-4">
        <figure>
          <img
            class="object-cover object-left-top rounded-xl drop-shadow-xl"
            src="~/assets/images/Concrete Slicer.jpg"
            alt=""
          />
        </figure>
      </div>
      <div class="col-span-3 mx-3 pl-4 text-slate-200 text-2xl">
        <h2 class="text-lime-400">Slicer software</h2>
        <p class="text-lg mt-4 text-justify">
          During the first semester of academic year 2021-2022, two other
          students had already participated in this project and created the
          foundation for slicer software that the printer could use. Because of
          the research done by other teams on the hardware of the printer, a
          custom slicer software was needed that was seemlessly integrated into
          the new technologies.
        </p>
        <p class="text-lg mt-4 text-justify">
          We expanded upon the slicer software that was created in the
          GrassHopper plugin that comes with the 3D rendering software
          "Rhinoceros3D". For this we needed to understand the concepts of
          lines, arcs, polylines and other geometric entities, especially how
          these behaved on a code level. Using the RhinoCommon SDK and Visual
          Studio we started exploring the language of C#.
        </p>
      </div>
      <div class="col-span-2 col-start-1 mx-3 pl-4 text-slate-200 text-2xl">
        <h2 class="text-lime-400">Node Red Visualisation</h2>
        <p class="text-lg mt-4 text-justify">
          Apart from the actual slicing software, we also made improvements on
          data logging and visualisation. This is still a work in progress and
          will surely be continued next year. The idea is to simplify reports
          and make more improvements on the printing process using the knowledge
          gathered from the historical data.
        </p>
        <figure class="mt-4">
          <img
            class="object-cover object-left-top rounded-xl drop-shadow-xl"
            src="~/assets/images/Node Red.jpg"
            alt=""
          />
        </figure>
      </div>
      <div class="col-span-2 col-start-3 mx-3 pl-4 text-slate-200 text-2xl">
        <h2 class="text-lime-400">G-code and Valve</h2>
        <p class="text-lg mt-4 text-justify">
          The biggest challenge for this project wast to allow the newly
          implemented valve on the extruder to respond to the gcode that was
          generated by the slicer software. Opening and closing the valve needed
          to be timed and placed between the regular commands of extrusion and
          movement.
        </p>
        <p class="text-lg mt-4 text-justify"></p>
      </div>
      <div class="col-span-1 mx-3 pl-4">
        <figure>
          <img
            class="object-cover object-left-top rounded-xl drop-shadow-xl"
            src="~/assets/images/Concrete Valve.jpg"
            alt=""
          />
        </figure>
      </div>
      <div class="col-span-2 mx-auto pl-4">
        <figure>
          <img
            class="object-cover object-left-top rounded-xl drop-shadow-xl"
            src="~/assets/images/ConcretePrinter grades.png"
            alt=""
          />
        </figure>
      </div>
    </div>
  </div>
</template>

<script>
export default {
  name: 'ConcretePrinter',
  data: () => ({
    title: '3D Concrete Printing',
    github: 'https://github.com/itfactory-di/3DCP_Slicer_Grasshopper3d',
    images: [
      {
        id: 1,
        name: 'Csharp',
        url: 'https://docs.microsoft.com/en-us/dotnet/csharp/',
      },
      { id: 2, name: 'Docker', url: 'https://www.docker.com/' },
      {
        id: 3,
        name: 'OPC UA',
        url: 'https://opcfoundation.org/about/opc-technologies/opc-ua/',
      },
      { id: 4, name: 'Node Red', url: 'https://nodered.org/' },
      { id: 5, name: 'Rhinoceros3D', url: 'https://www.rhino3d.com/' },
      { id: 6, name: 'GrassHopper', url: 'https://www.grasshopper3d.com/' },
    ],
    poster: 'ConcretePrinter',
  }),
  mounted() {},
  methods: {},
}
</script>

<style scoped></style>
